### ISSUE TITLE
Implicit add to trust store

### ISSUE THREAD

**Issue by dpeddi** [veithen/visualwas#2]
Req:

i'd like to use your visualwas in a non-interactive project. 

It would be nice to add a properties or implement a protocol to implicit add to the truststore the certificate.

**Comment by veithen** [comment]
It depends on what exactly you are trying to achieve. If you simply want to trust the peer without validating the certificate at all, then you would configure a trust manager that accepts any certificate.

**Comment by gknepper** [comment]
Debug with: **_./visualvm --jdkhome ../../jdk1.8.0_191 --nosplash -J-Dnetbeans.logger.console=true_**

INFO [com.github.veithen.visualwas.env.WebSphereClassLoaderProvider]: Successfully created class loader for WebSphere runtime at /opt/IBM/WebSphere/AppServer
java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy18.getServerMBean(Unknown Source)
        at com.github.veithen.visualwas.connector.impl.ConnectorImpl.getServerMBean(ConnectorImpl.java:63)
        at com.github.veithen.visualwas.jmx.soap.SOAPJMXConnector.internalConnect(SOAPJMXConnector.java:157)
        at com.github.veithen.visualwas.jmx.soap.SOAPJMXConnector.connect(SOAPJMXConnector.java:116)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at com.github.veithen.visualwas.WebSpherePropertiesPanel$8.run(WebSpherePropertiesPanel.java:305)
Caused by: javax.management.InstanceNotFoundException: No MBean of type Perf found
        at com.github.veithen.visualwas.connector.proxy.SingletonMBeanLocator$1$1.onSuccess(SingletonMBeanLocator.java:74)
        at com.github.veithen.visualwas.connector.proxy.SingletonMBeanLocator$1$1.onSuccess(SingletonMBeanLocator.java:62)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1058)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1029)
        at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:675)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:105)
        at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1033)
        at com.github.veithen.visualwas.connector.proxy.SingletonMBeanLocator$1.onSuccess(SingletonMBeanLocator.java:60)
        at com.github.veithen.visualwas.connector.proxy.SingletonMBeanLocator$1.onSuccess(SingletonMBeanLocator.java:50)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1058)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1029)
        at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:675)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:105)
        at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1033)
        at com.github.veithen.visualwas.connector.proxy.SingletonMBeanLocator.locateMBean(SingletonMBeanLocator.java:48)
        at com.github.veithen.visualwas.client.pmi.ConfigsLoaderInterceptor.produceValue(ConfigsLoaderInterceptor.java:40)
        at com.github.veithen.visualwas.connector.feature.ContextPopulatingInterceptor.invoke(ContextPopulatingInterceptor.java:47)
        at com.github.veithen.visualwas.connector.feature.ContextPopulatingInterceptor.invoke(ContextPopulatingInterceptor.java:32)
        at com.github.veithen.visualwas.connector.impl.InterceptorHandler.invoke(InterceptorHandler.java:40)
        at com.github.veithen.visualwas.connector.mapped.InvocationInterceptor.invoke(InvocationInterceptor.java:57)
        at com.github.veithen.visualwas.connector.mapped.InvocationInterceptor.invoke(InvocationInterceptor.java:30)
        at com.github.veithen.visualwas.connector.impl.InterceptorHandler.invoke(InterceptorHandler.java:40)
        at com.github.veithen.visualwas.connector.impl.AdminServiceFactory$1.invoke(AdminServiceFactory.java:51)
        at com.github.veithen.visualwas.framework.proxy.InvocationStyle$1.invoke(InvocationStyle.java:43)
        at com.github.veithen.visualwas.framework.proxy.InvocationHandlerDelegate.invoke(InvocationHandlerDelegate.java:34)
        at com.github.veithen.visualwas.framework.proxy.ProxyInvocationHandler.internalInvoke(ProxyInvocationHandler.java:57)
        at com.github.veithen.visualwas.framework.proxy.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:52)
        ... 6 more

**Comment by veithen** [comment]
I assume the last comment actually refers to issue #5.
