### ISSUE TITLE
com.github.veithen.visualwas.mxbeans_1.0.0.jar is not working on J9 Java 8

### ISSUE THREAD

**Issue by gknepper** [veithen/visualwas#3]
When putting the com.github.veithen.visualwas.mxbeans_1.0.0.jar inside /plugins directory the plugin works only when using Java 7 on server side (WAS).

**Comment by veithen** [comment]
Reproducible with the integration tests when switching to ibmcom/websphere-traditional:9.0.0.7-profile as the base Docker image in the root POM.

Error message:

```
a44349> java.lang.ClassCastException: com.ibm.java.lang.management.internal.ClassLoadingMXBeanImpl incompatible with javax.management.DynamicMBean
a44349>         at com.github.veithen.visualwas.mxbeans.PlatformMXBeansRegistrant.registerMBean(PlatformMXBeansRegistrant.java:166)
a44349>         at com.github.veithen.visualwas.mxbeans.PlatformMXBeansRegistrant.start(PlatformMXBeansRegistrant.java:129)
```
